whiskey_price = float(input())
water_amount = float(input())
wine_amount = float(input())
champagne_amount = float(input())
whiskey_amount = float(input())
champagne_price = (float(whiskey_price) * 0.50)
water_price = (float(champagne_price) * 0.10)
wine_price = (float(champagne_price) * 0.40)
whiskey_cost = float(whiskey_amount * whiskey_price)
water_cost = float(water_amount * water_price)
wine_cost = float(wine_amount * wine_price)
champagne_cost = float(champagne_amount * champagne_price)
total_cost = whiskey_cost + water_cost + champagne_cost + wine_cost
print(f'{total_cost:.2f}')