x1 = float(input())
y1 = float(input())
x2 = float(input())
y2 = float(input())
area = float(abs(x1 - x2) * abs(y1 - y2))
perimeter = float(2 * (abs(x1 - x2) + abs(y1 - y2)))
print(f'{area:.2f}')
print(f'{perimeter:.2f}')