whiskey_price = float(input())
beer_amount = float(input())
wine_amount = float(input())
rakia_amount = float(input())
whiskey_amount = float(input())
rakia_price = float(whiskey_price / 2)
wine_price = float (rakia_price * 0.60)
beer_price = float(rakia_price * 0.20)
total_cost = float(whiskey_amount * whiskey_price + beer_amount * beer_price + rakia_price * rakia_amount + wine_amount * wine_price)
print(f'{total_cost:.2f}')
