days = int(input())
pastry_chefs = int(input())
cakes = int(input())
waffles = int(input())
pancakes = int(input())
cake_cost = float(45)
waffle_cost = float(5.80)
pancake_cost = float(3.20)
cakes_amount = float(days * pastry_chefs * cakes * cake_cost)
waffles_amount = float(days * pastry_chefs * waffles * waffle_cost)
pancakes_amount = float(days * pastry_chefs * pancakes * pancake_cost)
total_amount = float((cakes_amount + waffles_amount + pancakes_amount) * 7 / 8)
print(f'{total_amount:.2f}')
